### PR TITLE
Endianess hints support

### PR DESCRIPTION
**Pull request by ceztko**
As per #57 request (please, reopen the ticket), I ended up implementing the feature myself . I added a couple of tests cases, but in few days I should integrate into a big project of mines, largely improving coverage. I'm creating an early pull request, to receive some review. The core commit is 
338ba27, the other commits are cosmetics or better integration with MSVC.

### CODE REVIEW

**Comment by ceztko** [comment]
I integrated the code in big [library](https://github.com/ceztko/podofo/tree/PdfStringUTF8) that parses big endian utf-16 strings in PDF documents and run the tests there with success. Also I updated the code here with more test coverage, some added commodities and some cleanings. This is now a fully fledged submit.

**Comment by nemtrif** [comment]
Sorry, I don't see the point of this. I you find it useful. Feel free to fork the library.

**Comment by ceztko** [comment]
Nemanja, first: of course if you don't accept the pull request, for any reason, I will keep my forked version of the library, no problem. But please, would you explain why your're refusing the change as a whole? Your decision comes with no technical explanation and your answer is inexplicably brief. UTF-16 comes with 2 byte order schemes[1], little endian and big endian. This is officially documented in the UNICODE standard, chapter 2.6 Encoding Schemes[2]. It means that any time the string is serialized to a non volatile medium it will keep a specific memory layout and this must be assumed when de-serializing/reading the string again in RAM. This is the case for an important example as the PDF format[3], that often stores strings as UTF-16 Big-Endian, but it can be for any format that decides to serialize UTF-16 strings for interoperability: it will be either UTF-16BE or UTF-16LE. After this explanation, you answer really surprises me as I'm adding support for an official feature of UTF-16 (and actually also UTF-32 would need the same treatment[4]) in utfcpp, at the cost of just a single conditional check [5] in the conversion functions, that in the normal case is just "false". Would you mind be more explicit why you don't want this change in your library?

[1] https://en.wikipedia.org/wiki/UTF-16#Byte_order_encoding_schemes
[2] https://www.unicode.org/versions/Unicode13.0.0/UnicodeStandard-13.0.pdf
[3] https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdf_reference_archive/pdf_reference_1-7.pdf, 3.8.1 String Types
[4] https://en.wikipedia.org/wiki/Byte_order_mark#UTF-32
[5] https://github.com/ceztko/utfcpp/blob/33965576e8d8c020975a43b77ea586d3cfc8d35f/source/utf8/checked.h#L221

**Comment by ceztko** [comment]
Also ICU[1], which is the official provided library for handling unicode encoded text, has similar hints to handle endianess[2].

[1] http://site.icu-project.org/home
[2] https://sourceforge.net/p/icu/mailman/message/10422989/

**Comment by ceztko** [comment]
Any hope to receive further comment on this? Thanks

**Pull request closed without merging**
