### PR TITLE
Add support for compiling with exceptions disabled

### PR DESCRIPTION
**Pull request by Pierre-vh**
Hello!

I've been using this library for quite some time in one of my projects (Pierre-vh/Fox). It's truly an amazing library and it provides all of the features I need in a small footprint, so thank you for making this library!

However, in the long-term, I'd like to make my project exception-free (= compilable with `/EHs-c-` (MSVC) or `-fno-exceptions` (GCC/CLang)). UTFCPP is the only part of my project that still depends on exceptions so I've modified it a bit to make it work without exceptions enabled.

Do you think these changes have their place in the main branch? Maybe it can be useful to other people.

Note that my changes are just a quick prototype. I think that they can be improved, but I'll wait for your feedback/suggestions. All tests pass and MSVC doesn't complain (in the main library) with `/EHs-c-`. It would be great to test it on other compilers/platforms, especially CLang or GCC to see if it works there too. 

Please tell me what you think!

Sincerely,
Pierre van Houtryve

### CODE REVIEW

**Comment by nemtrif** [comment]
Hi Pierre,

Thanks for the input! I have thought about supporting a non-exception mode for a while. If you are interested, I asked a question about automatically detecting non-exception compiler options and it produced at least one interesting answer which is in line with to what you are suggesting: https://stackoverflow.com/questions/6487013/programmatically-determine-whether-exceptions-are-enabled .

The biggest problem I see with the current approach you are suggesting is the use of assert in the non-exception mode. Reading invalid UTF-8 is a common scenario and we don't want to suddenly start aborting the process if that happens.

Have you tried using the "unchecked" namespace in UTF-CPP library? Functions from that namespace should work fine with exceptions disabled. You just need to make sure the text is valid UTF-8 before using the unchecked functions - there is a function is_valid for that.

Another option would be to add a new set of checked API calls that returns error codes instead of exceptions. That should not be horribly hard to do; it's just that I haven't had any requests for that functionality until now.

Nem

**Comment by Pierre-vh** [comment]
Hi,
Thank you for the quick answer :)

I haven't thought about using functions from the unchecked namespace, maybe I can write an exception-free wrapper around them for my project.  I'll try to explore that over the next weeks!

Just out of curiosity, is reading bad UTF-8 that common when reading files

Pierre

**Comment by nemtrif** [comment]
Not sure what you mean by an "exception-free wrapper" - the unchecked functions are already exception free.

As for how common bad UTF-8 is, it really depends on where your text from. In many cases you don't even know the encoding of the file until you start reading it.

**Comment by Pierre-vh** [comment]
> Not sure what you mean by an "exception-free wrapper" - the unchecked functions are already exception free.

I mean writing my own `checked.h`  using different means of error-handling, like you suggested earlier:
> Another option would be to add a new set of checked API calls that returns error codes instead of exceptions

Anyway, I think this PR can be closed. Thank you for the discussion! :)

**Pull request closed without merging**
